### ISSUE TITLE
Update release on ansible-galaxy.

### ISSUE THREAD

**Issue by esolitos** [githubixx/ansible-role-cfssl#3]
Currently when downloading the role from ansible-galaxy it downloads the tagged version `2.0.1+R1.2.0`, which is missing a few commits.

Could you push the updates in a new version?

**Comment by githubixx** [comment]
I needed to delete older tags because since Galaxy changed their tag naming requirements all tags that don't met SemVer versioning scheme don't work anymore. So I deleted the old tags
```
v1.0.0_r1.2.0
v2.0.0_r1.2.0
v2.0.1_r1.2.0
v2.0.2_r1.2.0
v2.0.3_r1.2.0
```
So now only 
```
3.0.0+1.2.0
4.0.0+1.2.0
```
are left. If I now run `ansible-galaxy install githubixx.cfssl` it downloads `4.0.0+1.2.0` by default. Hope this helps.

**Comment by esolitos** [comment]
Yes indeed, the 4.0.0+1.2.0 is now installed by default, thanks!

PS: And thanks for the role as well. :)
